services:
  app:
    restart: always
    container_name: appBuild
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    depends_on: 
      - "mysql-db"
    networks:
      - minha_rede

  mysql-db:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - minha_rede

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8000:80"   # Porta HTTP para o Certbot verificar o domínio
      - "443:443" # Porta HTTPS para conexões seguras
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf    # Configuração do Nginx
    depends_on: 
      - "app"
    networks:
      - minha_rede

volumes:
  db:
networks:
  minha_rede:
    driver: bridge
