services:
  app:
    restart: always
    container_name: appBuild
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on: 
      - "mysql-db"
    networks:
      - minha_rede

  mysql-db:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - minha_rede
volumes:
  db:
networks:
  minha_rede:
    driver: bridge
