services:
  app:
    restart: always
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on: 
      - "mysql-db"
    networks:
      - minha_rede

  mysql-db:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - minha_rede

  mongo:
    image: mongo:8
    container_name: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - mongoDb:/data/db
      - mongoConfig:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - minha_rede

  redis:
    image: redis:7.4.2-alpine
    container_name: quiro-redis
    restart: always
    env_file:
      - .env
    volumes:
      - redisDb:/data
    ports:
      - "6379:6379"
    networks:
      - minha_rede

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports: 
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - minha_rede

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - "3001:3000"
    networks:
      - minha_rede

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - minha_rede

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command:
      -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - minha_rede

volumes:
  db:
  mongoDb:
  loki_data:
  redisDb:
  mongoConfig:
networks:
  minha_rede:
    driver: bridge

