services:
  mysql-db:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db: