export enum ETableNames {
  USERS = "users",
  USER_FINGERPRINTS = "user_fingerprints",
  PATIENTS = "patients",
  LOCATIONS = "locations",
  SERVICES = "services",
  ANAMNESIS = "anamnesis",
  DIAGNOSTICS = "diagnostics",
  PROGRESS = "progress",
  REFRESH_TOKEN = "refresh_token",
  SCHEDULES = "schedules",
  BEFORE_SCHEDULE_MESSAGES = "before_schedule_messages",
  AFTER_SCHEDULE_MESSAGES = "after_schedule_messages",
  BIRTHDAY_MESSAGES = "birthday_messages",
  FINANCES = "finances",
  EXAMS = "exams",
  NOT_MESSAGE_PATIENTS = "notMessagePatients",
  BLOCK_SCHEDULES = "block_schedules",
  EVENT_SUGGESTIONS = "event_suggestions",
  PAIN_SCALES = "pain_scales",
  WHATSAPP_INSTANCES = "whatsapp_instances",
  WHATSAPP_MESSAGE_LOGS = "whatsapp_message_logs",
  MESSAGE_SEND_STRATEGIES = "message_send_strategies",
  USER_MESSAGE_SEND_STRATEGY = "user_message_send_strategy",
  /** Campanhas com regra “único por paciente” (sem FK para `message_send_strategies`). */
  USER_CAMPAIGN_UNIQUE_SEND_STRATEGY = "user_campaign_unique_send_strategy",
}
