export enum ETableNames {
  USERS = "users",
  PATIENTS = "patients",
  LOCATIONS = "locations",
  SERVICES = "services",
  ANAMNESIS = "anamnesis",
  DIAGNOSTICS = "diagnostics",
  PROGRESS = "progress",
  REFRESH_TOKEN = "refresh_token",
  SCHEDULES = "schedules",
  FINANCES = "finances",
  EXAMS = "exams",
  NOT_MESSAGE_PATIENTS = "notMessagePatients",
  BLOCK_SCHEDULES = "block_schedules",
  EVENT_SUGGESTIONS = "event_suggestions",
  PAIN_SCALES = "pain_scales",
}
